lectures/urls.py
from django.contrib import admin
from django.urls import path, include

from lessons.urls import (
    urlpatterns_auth,
    urlpatterns_lessons, 
    urlpatterns_materials,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path("lessons/", include(urlpatterns_lessons)),
    path("materials/", include(urlpatterns_materials)),
    path("accounts/", include(urlpatterns_auth)),
]

lessons/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views

urlpatterns_lessons = [
    path("", view=views.all_lessons, name="fetch-all-lessons"),
    path("<slug:slug>/", view=views.lesson, name="fetch-one-lesson"),
    path("<slug:slug>/edit", view=views.edit_lesson, name="edit-lesson"),
    path(
        "<slug:lesson_slug>/materials",  # lessons/<slug>/materials
        view=views.create_material, 
        name="create-material",
    ),
]


urlpatterns_materials = [  # /materials/
    path("<slug:slug>", view=views.material, name="fetch-one-material"),
    path("<slug:slug>/share", view=views.share_material, name="share-material"),
]


urlpatterns_auth = [
    path("register/", view=views.register, name="register"),
    path("login/", view=auth_views.LoginView.as_view(), name="login"),
    path("logout/", view=auth_views.LogoutView.as_view(), name="logout"),
    
    path(
        "password_reset/", 
        view=auth_views.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/done",
        view=auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        view=auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm"
    ),
    path(
        "reset/done",
        view=auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

lessons/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


class WithTimeTracking(models.Model):

    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    class Meta:
        abstract = True


class MaterialEntity(
    WithTimeTracking,
    models.Model
):
    """
    Model for Materials entity.
    """

    THEORY_MATERIAL = 'theory'
    PRACTICE_MATERIAL = 'practice'
    TEST_MATERIAL = 'test'
    MATERIAL_TYPES = (
        (THEORY_MATERIAL, 'Theoretic Materials'), 
        (PRACTICE_MATERIAL, 'Practical Material'),
        (TEST_MATERIAL, 'Testing Material'),
    )

    title = models.CharField(max_length=64)
    slug = models.SlugField(max_length=8)
    body = models.TextField()
    material_type = models.CharField(
        max_length=16, 
        choices=MATERIAL_TYPES,
        default=THEORY_MATERIAL,
    )

    def __str__(self) -> str:
        return self.slug
    
    def get_absolete_url(self) -> str:
        return reverse("fetch-one-material", args=[self.slug])


class LessonEntity(
    WithTimeTracking,
    models.Model,
):
    """
    Model for Lesson entity.
    """

    title = models.CharField(max_length=64)
    slug = models.SlugField(max_length=8)
    description = models.TextField()

    materials = models.ManyToManyField(
        MaterialEntity, 
        related_name="lessons",
    )

    def __str__(self) -> str:
        return self.slug

    def get_absolete_url(self) -> str:
        return reverse("fetch-one-lesson", args=[self.slug])


class CommentEntity(
    WithTimeTracking,
    models.Model,
):
    lesson = models.ForeignKey(
        LessonEntity,
        on_delete=models.CASCADE,
        related_name="comments",
    )

    body = models.TextField()
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        related_name="user_comments",
        null=True,
    )

    def __str__(self) -> str:
        return f"COMMENT <{self.body}>"


class ProfileEntity(models.Model):
    """
    Model for Profile entity.
    """

    birthday = models.DateField(null=True, blank=True)
    avatar = models.ImageField(upload_to="avatars", null=True, blank=True)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self) -> str:
        return self.user

lessons/forms.py
from django import forms
from django.contrib.auth.models import User

from . import models


class MaterialForm(forms.ModelForm):
    class Meta:
        model = models.MaterialEntity
        fields = (
            "title", 
            "body", 
            "material_type",
        )


class EmailMaterialForm(forms.Form):
    my_name = forms.CharField(max_length=20)
    to_email = forms.EmailField()
    comment = forms.CharField(widget=forms.Textarea)


class LessonForm(forms.ModelForm):
    class Meta:
        model = models.LessonEntity
        fields = (
            "title",
            "description",
        )


class RegistrationForm(forms.ModelForm):

    password = forms.CharField(
        label="password",
        widget=forms.PasswordInput,
    )

    password2 = forms.CharField(
        label="repeat password",
        widget=forms.PasswordInput,
    )

    class Meta:
        model = User
        fields = (
            "username", 
            "first_name", 
            "email",
        )

    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password"] != cd["password2"]:
            raise forms.ValidationError("Passwords are not equal")
        return cd["password2"]

lessons/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse
from django.core.mail import send_mail

from . import forms
from . import models


@login_required
def all_lessons(request):
    lessons = models.LessonEntity.objects.all()
    return render(
        request, 
        "lessons/lessons.html", 
        {
            "lessons": lessons,
        })


@login_required
def lesson(request, slug):    
    lesson = get_object_or_404(models.LessonEntity, slug=slug)
    return render(request, "lessons/lesson.html", {"lesson": lesson})


@login_required
def edit_lesson(request, slug):
    lesson = get_object_or_404(models.LessonEntity, slug=slug)
    if request.method == "POST":
        lesson_form = forms.LessonForm(request.POST, instance=lesson)
        if lesson_form.is_valid():
            lesson_form.save()
        return render(
            request,
            "lessons/lesson.html",
            {"lesson": lesson},
        )
    else:
        lesson_form = forms.LessonForm(instance=lesson)
        return render(
            request,
            "lessons/edit.html",
            {
                "form": lesson_form,
                "lesson": lesson,
            },
        )


@login_required
def material(request, slug):
    material = get_object_or_404(models.MaterialEntity, slug=slug)
    return render(request, "materials/material.html", {"material": material})


@login_required
def create_material(request, lesson_slug):
    lesson = get_object_or_404(models.LessonEntity, slug=lesson_slug)
    if request.method == "POST":
        material_form = forms.MaterialForm(request.POST)
        if material_form.is_valid():
            new_material = material_form.save()
            new_material.slug = f"MATERIAL-{new_material.id}"
            new_material.lessons.add(lesson)
            new_material.save()
            return render(
                request, 
                "lessons/lesson.html", 
                {"lesson": lesson},
            )
        else:
            render(
                request, 
                "materials/create.html", 
                {
                    "material_types": models.MaterialEntity.MATERIAL_TYPES,
                    "title_error": material_form.errors["title"][0],
                    "body_error": material_form.errors["body"][0],
                }  
            )

    return render(
        request, 
        "materials/create.html", 
        {
            "material_types": models.MaterialEntity.MATERIAL_TYPES,
        }
    )


def _prepare_email(material, cd, request):
    uri = request.build_absolute_uri(material.get_absolete_url())
    body = (
        f"<a href='{uri}'>{material.title}</a> was recommended to you by {cd['my_name']}.\n\n"
        f"Comment: {cd['comment']}"
    )
    subject = f"{cd['my_name']} recommends you {material.title}"
    return subject, body


def share_material(request, slug):
    material = get_object_or_404(models.MaterialEntity, slug=slug)
    is_sent = False
    if request.method == "POST":
        form = forms.EmailMaterialForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            subject, body = _prepare_email(material, cd, request)
            send_mail(subject, body, "admin@admin.com", [cd["to_email"]])
            is_sent = True
    else:
        form = forms.EmailMaterialForm()
    return render(
        request,
        "materials/share.html",
        {
            "form": form,
            "material": material,
            "is_sent": is_sent,
        }
    )


def register(request):
    if request.method == "POST":
        registration_form = forms.RegistrationForm(request.POST)
        if registration_form.is_valid():
            new_user = registration_form.save(commit=False)
            new_user.set_password(registration_form.cleaned_data["password"])
            new_user.save()
            models.ProfileEntity.objects.create(user=new_user)
            return render(
                request,
                "registration/registration_complete.html",
                {"new_user": new_user},
            )
        else:
            return HttpResponse("Bad credentials")

    registration_form = forms.RegistrationForm()
    return render(
        request,
        "registration/register.html",
        {"form": registration_form},
    )

lessons/templates/lessons/edit.html
{% extends "base.html" %}

{% block title %}
    Edit Lesson
{% endblock %}

{% block content %}
<div class="container">
    <div class="lessons-header">
        <h1>Edit lesson "{{ lesson.slug }}"</h1>
    </div>  
    <form action="./edit" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_title" class="form-label">Title</label>
            <input 
                id="id_title"
                name="title"
                type="text" 
                class="form-control" value="{{ form.title.value }}"
                maxlength="64"
                required
            />
        </div>
        <div class="mb-3">
            <label for="id_description" class="form-label">Description</label>
            <textarea 
                id="id_description" 
                name="description"
                type="text" 
                class="form-control" 
                rows="12"
                required
            >{{ form.description.value }}</textarea>
        </div>
        <div class="mb-3">
            <input 
                type="submit" 
                class="btn btn-success" 
                value="Save Changes"
            >
        </div>
    </form>
</div>
{% endblock %}

lessons/templates/lessons/lesson.html
{% extends "base.html" %}

{% block title %}
    {{ lesson.title }}
{% endblock %}

{% block content %}
<div class="container">  
    <div class="lessons-header">
        <h1>{{ lesson.title }}</h1>
    </div>

    <p>{{ lesson.description }} </p>

    <div class="list-group materials-list">
        <div class="list-group-item list-group-item-secondary" aria-current="true">
            <div class="d-flex w-100 justify-content-between align-items-center">
                <h5 class="mb-1">Materials</h5>
                <a class="btn btn-primary" href="{% url "create-material" lesson.slug %}" role="button">Add</a>
            </div>
        </div>
        {% for m in lesson.materials.all %}
        <a href="{{ m.get_absolete_url }}" class="list-group-item list-group-item-action" aria-current="true">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ m.title }}</h5>
            <small>{{ m.created_at }}</small>
          </div>
          <small>{{ m.material_type }}</small>
        </a>
        {% endfor %}
    </div>

    <div class="list-group comments">
        <div class="list-group-item list-group-item-secondary" aria-current="true">
            <div class="d-flex w-100 justify-content-between align-items-center">
                {% with lesson.comments.count as total_comments %}
                <h5 class="mb-1">Comments <span class="badge bg-danger rounded-pill">{{ total_comments }}</span></h5>
                {% endwith %}
            </div>
        </div>
        {% for c in lesson.comments.all %}
        <div class="list-group-item list-group-item-action" aria-current="true">
            <p class="mb-1">{{ c.body }}</p>
            <small>{{ c.created_by }} at {{ c.created_at }}</small>
        </div>
        {% empty %}
            <p>No comments.</p>
        {% endfor %}
    </div>

</div>
{% endblock %}

lessons/templates/lessons/lessons.html
{% extends "base.html" %}

{% block title %}
    All lessons
{% endblock %}

{% block content %}
    <div>
        <div class="lessons-header">
            <h1> List of my lessons </h1>
        </div>
        <div class="lessons-list">
            {% for l in lessons %}
            <div class="lesson">
                <h2 class="red-text">{{ l.title }}</h2>
                <p>{{ l.description }}</p>
                <a href="{{ l.get_absolete_url }}">link</a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}